# Generated by Django 4.2.16 on 2024-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='photo',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
