# Generated by Django 4.2.16 on 2024-12-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_menuitem_photo_menuitem_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
