# Generated by Django 4.2.16 on 2024-12-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_partners', to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('active', 'Active'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('inactive', 'Inactive')], default='received', max_length=20),
        ),
    ]
